"""added uniconstraint to stock table for item_id

Revision ID: c61b58880bb0
Revises: c281461cf6cc
Create Date: 2026-04-27 19:18:53.978525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61b58880bb0'
down_revision: Union[str, Sequence[str], None] = 'c281461cf6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_stock_item_id', 'stocks', ['item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stock_item_id', 'stocks', type_='unique')
    # ### end Alembic commands ###
