"""import models from python module

Revision ID: eddd821f4b08
Revises: fd91b65d3153
Create Date: 2026-04-22 16:11:02.235330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddd821f4b08'
down_revision: Union[str, Sequence[str], None] = 'fd91b65d3153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_item_name'), 'items', ['item_name'], unique=False)
    op.create_table('users_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('nic', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_details_address'), 'users_details', ['address'], unique=False)
    op.create_index(op.f('ix_users_details_email'), 'users_details', ['email'], unique=True)
    op.create_index(op.f('ix_users_details_id'), 'users_details', ['id'], unique=False)
    op.create_index(op.f('ix_users_details_name'), 'users_details', ['name'], unique=True)
    op.create_index(op.f('ix_users_details_nic'), 'users_details', ['nic'], unique=True)
    op.create_index(op.f('ix_users_details_phone'), 'users_details', ['phone'], unique=True)
    op.create_index(op.f('ix_users_details_role'), 'users_details', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_details_role'), table_name='users_details')
    op.drop_index(op.f('ix_users_details_phone'), table_name='users_details')
    op.drop_index(op.f('ix_users_details_nic'), table_name='users_details')
    op.drop_index(op.f('ix_users_details_name'), table_name='users_details')
    op.drop_index(op.f('ix_users_details_id'), table_name='users_details')
    op.drop_index(op.f('ix_users_details_email'), table_name='users_details')
    op.drop_index(op.f('ix_users_details_address'), table_name='users_details')
    op.drop_table('users_details')
    op.drop_index(op.f('ix_items_item_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
